### ISSUE TITLE
Hash checking throws error while using CopyWebpackPlugin

### ISSUE THREAD

**Issue by burnpiro** [rubenspgcavalcante/webpack-chrome-extension-reloader#25]
**Type:**
- [x] bug  
- [ ] feature
- [ ] enhancement
- [ ] question
 
**Environment:**
 - OS: Ubuntu 17.10
 - Version: 0.6.2 
 
**Going to open a PR:**
- [ ] yes
- [x] no
 
**Description:**  
Hi, first of all great plugin :) I'm trying to use it with additional copying for extension popup page. If you add anything to CopyWebpackPlugin it doesn't generate new compilation hash and rejecting Promise in https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader/blob/master/src/utils/changes-triggerer.ts#L16 . Because of that whole build in interrupted with `error Command failed with exit code 1`. I know that you were trying to limit useless updates but in this case it won't work. I'm not sure what's the best solution to determine if there was a change in compilers output but maybe sth related with assets size (like react team does when comparing bundles). It works after removing that `if` and letting it reload extension each time webpack does sth.
```
return (hash: string): Promise<any> => {
    return server.signChange(reloadPage);
  };
```
I'm not expect you to change that because there is probably way better solution :)

**Comment by fgladisch** [comment]
I'm having the same problem. Maybe whe could control this behaviour through an option?

**Comment by RShergold** [comment]
I'm also getting this error a lot. Can we get some clarity on 

1. Why it needs to check that the hash has changed
2. Why it needs to throw an error if the hash has not changed

**Comment by burnpiro** [comment]
@1 To limit number of reloads (chrome has some security rules for extensions https://bugs.chromium.org/p/chromium/issues/detail?id=733209#c1)
@2 It doesn't, there is just a promise rejection and if you reject that promise it block flow in webpack and throws exception.

**Comment by rubenspgcavalcante** [comment]
Thanks for your feedback @burnpiro ,
First I'll _resolve_ instead of _reject_ in cases of same hash (@RShergold , I'll change the name of the constant as it is more a warning than a error), but I'll maintain the hash check just to not trigger too much updates, raising the chrome auto reload block.

I'll research another way to check if the extension changed when using the CopyWebpackPlugin. Much probably is because the copied files aren't checked by webpack, as they're not part of the processed bundle. Anyway is just a thought and I need to check that.

**Comment by rubenspgcavalcante** [comment]
So, files processed by CopyWebpackPlugin does emit new compilation when changed, but don't affect the compilation hash. It doesn't generate a chunkname too. :/
I need to check with that plugin team if this is a normal behaviour, and if it is, how to track if the files under it watch were changed (or triggered the emit)

**Comment by rubenspgcavalcante** [comment]
Opened, waiting response:
https://github.com/webpack-contrib/copy-webpack-plugin/issues/203

**Comment by rubenspgcavalcante** [comment]
After talk with the WCP team, I've implemented a way to check the md5 hashes of all emitted assets. Turns out is a over engineering solution to a thing that should be a small check for a rare case.
Thinking in that way, I'll just follow @burnpiro suggestion and if anything is emitted just sign the changes to the extension injected listener.
I'll open a PR and release a patch version right now 👍 .
